# Generated by Django 3.1.7 on 2021-03-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMaster', '0002_auto_20210312_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='date_before_used',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='date_of_import',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='qaulity',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=None, max_length=10),
        ),
    ]
